# NumPy入门
    本章将详细介绍NumPy(Numerical Python的简称)提供了高效存储和操作密集数据缓存的借口.在某些方面,NumPy数组和Python内置的列表类型非常相似.但是随着数组在维度上变大,NumPy数组提供了更加高效的存储和数据操作.NumPy数组几乎是整个Python数据科学工具生态系统的核心.因此不管你对数据科学的哪个方面感兴趣,花点时间学习如何有效使用NumPy都是非常值得的.
    


### 2.1.5 创建几个数组

In [1]:
import numpy as np
# 创建一个长度为10的数组, 数组的值都是0
# 是zeros, 不是zero
np.zeros(10, dtype=int)     
# 此函数有啥作用?

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
# 创建一个3 * 5的浮点型数组, 数组的值都是1
np.ones((3,5),dtype=float)
# 3 * 5 表示3行*5列, 输入代码是圆括号本身是成对出现的, 如果手动添加或者剪切, 可能会导致错误

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
# 创建一个3 * 5的浮点型数组, 数组的值都是3.14
np.full((3,5), 3.14)
# zeros,ones,full都是np下的函数, 可以创建数组.

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])